import { storageService } from './storage';
import { aiInferenceClient } from './aiInferenceClient';

interface CaptionResult {
  caption: string;
  confidence: number;
}

/**
 * AI captions are generated by the Memoria AI inference service (Gemini).
 */
export class CaptionService {
  async generateCaption(storagePath: string, mimeType: string): Promise<CaptionResult> {
    const imageUrl = await storageService.getSignedUrl('memories', storagePath, 900);
    return aiInferenceClient.generateCaption(imageUrl, mimeType);
  }
}
