import { storageService } from './storage';
import { aiInferenceClient } from './aiInferenceClient';
export interface FaceDetectionResponse {
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    label?: string;
  }
interface FaceDetectionResult {
    boundingBoxes: FaceDetectionResponse[];
    embeddings: number[][];
    photoId: string;
    count: number;
  }
interface FaceEmbeddingResult {
    embedding: number[];
    photoId: string;
    coverFaceId: number;
  }
/**
 * AI captions are generated by the Memoria AI inference service (Gemini).
 */
export class faceDetectionService {
  async postFaceDetection(storagePath: string, mimeType: string): Promise<FaceDetectionResult> {
    const imageUrl = await storageService.getSignedUrl('memories', storagePath, 900);
    return aiInferenceClient.postFaceDetection(imageUrl, mimeType);
  }
}
