import { storageService } from './storage';
import { aiInferenceClient } from './aiInferenceClient';

interface FaceDetectionResponse { x?: number; y?: number; width?: number; height?: number; label?: string; }

/**
 * AI captions are generated by the Memoria AI inference service (Gemini).
 */
export class faceDetectionService {
  async postFaceDetection(storagePath: string, mimeType: string): Promise<FaceDetectionResponse[]> {
    const imageUrl = await storageService.getSignedUrl('memories', storagePath, 900);
    return aiInferenceClient.postFaceDetection(imageUrl, mimeType);
  }
}